// ============================================================
// OUTRIQ — Mock Data
// Based on AI Marketing Agent Blueprint (Aniekan Israel, April 2026)
// ============================================================

export const PRODUCTS = [
  {
    id: 'chopfit-lagos-001',
    name: 'ChopFit Lagos',
    category: 'Food & Fitness',
    location: 'Lagos, Nigeria',
    description: 'Fresh, calorie-counted meals delivered to your door in Lagos. We prepare healthy meal prep for busy professionals.',
    targetCustomer: 'Health-conscious professionals aged 25-40 in Lagos',
    website: 'www.chopfit.ng',
    status: 'active',
    createdAt: '2026-03-15',
    emoji: '🥗',
    color: '#10b981',
    pip: {
      valueProp: 'Saves busy professionals time while keeping them healthy',
      painPoints: ['No time to cook healthy meals', 'Struggling to maintain diet with busy schedule', 'Tired of unhealthy fast food options'],
      searchTerms: ['healthy food delivery Lagos', 'meal prep service Nigeria', 'diet food delivery Lekki', 'calorie counted meals Lagos'],
      platforms: ['Instagram', 'X/Twitter', 'Nairaland', 'LinkedIn'],
      emotionalTriggers: ['Feeling guilty about eating junk food again', 'Wanting to look and feel better'],
      contentAngles: ['What if your meals were handled for the whole week?', 'Lagos professionals switching to this'],
    },
    metrics: { signals: 247, actions: 89, leads: 31, impressions: 12400, clicks: 843 },
    matchScore: 94,
  },
  {
    id: 'techflow-ng-002',
    name: 'TechFlow Academy',
    category: 'Education & Tech',
    location: 'Nigeria (Remote)',
    description: 'Online bootcamp for aspiring software developers in Nigeria. 12-week intensive program with job placement support.',
    targetCustomer: 'Unemployed graduates aged 22-35 looking to transition into tech',
    website: 'www.techflowng.com',
    status: 'active',
    createdAt: '2026-03-22',
    emoji: '💻',
    color: '#8b5cf6',
    pip: {
      valueProp: 'Fastest path from zero to employed software developer in Nigeria',
      painPoints: ['Unemployed with a degree', 'No tech skills or experience', 'Unsure how to break into tech'],
      searchTerms: ['learn coding Nigeria', 'tech bootcamp Lagos', 'software developer course Nigeria', 'how to become a developer Nigeria'],
      platforms: ['X/Twitter', 'Reddit', 'LinkedIn', 'Nairaland'],
      emotionalTriggers: ['Fear of being left behind in the digital economy', 'Desire for financial independence'],
      contentAngles: ['How this Lagos graduate went from unemployed to ₦400k/month developer in 3 months'],
    },
    metrics: { signals: 318, actions: 134, leads: 58, impressions: 28600, clicks: 1920 },
    matchScore: 91,
  },
  {
    id: 'legaledge-003',
    name: 'LegalEdge Nigeria',
    category: 'Legal Services',
    location: 'Abuja & Lagos, Nigeria',
    description: 'Affordable legal services for small businesses and startups in Nigeria. Contracts, registration, compliance.',
    targetCustomer: 'Small business owners and startup founders aged 28-45',
    website: 'www.legaledge.ng',
    status: 'active',
    createdAt: '2026-04-01',
    emoji: '⚖️',
    color: '#06b6d4',
    pip: {
      valueProp: 'Protect your business with expert legal advice at a fraction of traditional costs',
      painPoints: ['Afraid of legal issues destroying business', 'Cannot afford a full-time lawyer', 'Confused by business registration requirements'],
      searchTerms: ['business registration Nigeria', 'startup lawyer Lagos', 'CAC registration help', 'legal advice small business Nigeria'],
      platforms: ['LinkedIn', 'X/Twitter', 'Nairaland', 'Facebook Groups'],
      emotionalTriggers: ['Fear of losing business to avoidable legal problems'],
      contentAngles: ['5 legal mistakes Nigerian startups make that kill their business'],
    },
    metrics: { signals: 156, actions: 67, leads: 23, impressions: 8900, clicks: 612 },
    matchScore: 87,
  },
  {
    id: 'fitgear-abuja-004',
    name: 'FitGear Abuja',
    category: 'Health & Fitness',
    location: 'Abuja, Nigeria',
    description: 'Premium home gym equipment delivered and installed in Abuja. Quality gym gear at fair prices.',
    targetCustomer: 'Fitness enthusiasts aged 25-50 in Abuja who want to work out at home',
    website: 'www.fitgearabuja.com',
    status: 'paused',
    createdAt: '2026-04-05',
    emoji: '🏋️',
    color: '#f59e0b',
    pip: {
      valueProp: 'Build your dream home gym without the hassle',
      painPoints: ['Gym membership too expensive long-term', 'No time to drive to gym', 'Want a private workout space'],
      searchTerms: ['home gym equipment Abuja', 'buy gym equipment Nigeria', 'home workout equipment delivery Nigeria'],
      platforms: ['Instagram', 'Facebook Groups', 'X/Twitter'],
      emotionalTriggers: ['Wanting gym body without gym crowds', 'Desire for convenient fitness solution'],
      contentAngles: ['Why Abuja professionals are ditching gym memberships for home setups'],
    },
    metrics: { signals: 89, actions: 28, leads: 9, impressions: 4200, clicks: 287 },
    matchScore: 78,
  },
  {
    id: 'saferent-lagos-005',
    name: 'SafeRent Lagos',
    category: 'Real Estate',
    location: 'Lagos, Nigeria',
    description: 'Verified short-let apartments in Lagos. Safe, affordable, flexible accommodation for professionals and travelers.',
    targetCustomer: 'Professionals relocating to Lagos, business travelers, and people needing flexible housing',
    website: 'www.saferent.ng',
    status: 'active',
    createdAt: '2026-04-08',
    emoji: '🏠',
    color: '#f43f5e',
    pip: {
      valueProp: 'Find verified, safe, flexible accommodation in Lagos without the stress',
      painPoints: ['Scammed by fake property listings', 'Need flexible short-term accommodation', 'Relocating to Lagos and don\'t know where to start'],
      searchTerms: ['short let Lagos', 'furnished apartment Lagos', 'temporary accommodation Lagos', 'verified apartments Lagos'],
      platforms: ['Instagram', 'Facebook Groups', 'Nairaland', 'Google Search'],
      emotionalTriggers: ['Fear of being scammed in Lagos property market'],
      contentAngles: ['How to find a verified Lagos apartment without getting scammed'],
    },
    metrics: { signals: 203, actions: 76, leads: 34, impressions: 15300, clicks: 1104 },
    matchScore: 89,
  },
]

export const INTENT_SIGNALS = [
  {
    id: 'sig-001', platform: 'nairaland', platformLabel: 'Nairaland', platformKey: 'N',
    text: 'Abeg who knows where I fit get good healthy food delivery for Lekki? I don tire to cook after work.',
    signalType: 'question', matchedProduct: 'chopfit-lagos-001', score: 94, time: '2m ago',
    url: 'nairaland.com/food/5849201',
  },
  {
    id: 'sig-002', platform: 'twitter', platformLabel: 'X/Twitter', platformKey: 'X',
    text: 'Anyone know a good meal prep service in Lagos? Tired of ordering junk every night',
    signalType: 'need', matchedProduct: 'chopfit-lagos-001', score: 91, time: '5m ago',
    url: 'x.com/status/1234567',
  },
  {
    id: 'sig-003', platform: 'reddit', platformLabel: 'Reddit', platformKey: 'R',
    text: 'Looking for recommendations: best online coding bootcamp in Nigeria for 2026?',
    signalType: 'question', matchedProduct: 'techflow-ng-002', score: 88, time: '11m ago',
    url: 'reddit.com/r/nigeria/post',
  },
  {
    id: 'sig-004', platform: 'linkedin', platformLabel: 'LinkedIn', platformKey: 'Li',
    text: 'Any Nigerian startup founders here who can recommend a good affordable startup lawyer?',
    signalType: 'question', matchedProduct: 'legaledge-003', score: 86, time: '18m ago',
    url: 'linkedin.com/feed',
  },
  {
    id: 'sig-005', platform: 'nairaland', platformLabel: 'Nairaland', platformKey: 'N',
    text: 'I need to register my business with CAC but don\'t know how to start. Any help?',
    signalType: 'need', matchedProduct: 'legaledge-003', score: 92, time: '24m ago',
    url: 'nairaland.com/business',
  },
  {
    id: 'sig-006', platform: 'twitter', platformLabel: 'X/Twitter', platformKey: 'X',
    text: 'Want to learn software development in Nigeria. Where should I start? Feel free to drop resources',
    signalType: 'question', matchedProduct: 'techflow-ng-002', score: 85, time: '31m ago',
    url: 'x.com/status/7654321',
  },
  {
    id: 'sig-007', platform: 'instagram', platformLabel: 'Instagram', platformKey: 'Ig',
    text: 'Looking for verified short-let apartment in Lekki or VI for 3 months. Please DM or drop a link.',
    signalType: 'need', matchedProduct: 'saferent-lagos-005', score: 97, time: '38m ago',
    url: 'instagram.com/p/abc',
  },
  {
    id: 'sig-008', platform: 'google', platformLabel: 'Google Search', platformKey: 'G',
    text: 'Search trend: "healthy meal delivery Lagos" +340% volume this week',
    signalType: 'search', matchedProduct: 'chopfit-lagos-001', score: 89, time: '45m ago',
    url: 'trends.google.com',
  },
  {
    id: 'sig-009', platform: 'nairaland', platformLabel: 'Nairaland', platformKey: 'N',
    text: 'Where can I buy good quality home gym equipment in Abuja? Looking to set up a small gym at home.',
    signalType: 'question', matchedProduct: 'fitgear-abuja-004', score: 96, time: '52m ago',
    url: 'nairaland.com/fitness',
  },
  {
    id: 'sig-010', platform: 'quora', platformLabel: 'Quora', platformKey: 'Q',
    text: 'What is the best meal delivery service in Lagos in 2026?',
    signalType: 'question', matchedProduct: 'chopfit-lagos-001', score: 88, time: '1h ago',
    url: 'quora.com/questions',
  },
  {
    id: 'sig-011', platform: 'reddit', platformLabel: 'Reddit', platformKey: 'R',
    text: 'Thinking of relocating to Lagos for work. How do I find legitimate short-term accommodation?',
    signalType: 'question', matchedProduct: 'saferent-lagos-005', score: 93, time: '1h 10m ago',
    url: 'reddit.com/r/lagos',
  },
  {
    id: 'sig-012', platform: 'twitter', platformLabel: 'X/Twitter', platformKey: 'X',
    text: 'I have a business idea but no clue how to legally set it up in Nigeria. Thread incoming 🧵',
    signalType: 'need', matchedProduct: 'legaledge-003', score: 79, time: '1h 25m ago',
    url: 'x.com/status/8888',
  },
]

export const ACTIONS = [
  {
    id: 'act-001', type: 'respond', platform: 'nairaland',
    title: 'Response posted on Nairaland',
    desc: 'Recommended ChopFit Lagos to user asking about healthy food delivery in Lekki',
    product: 'ChopFit Lagos', status: 'success', time: '3m ago',
    metrics: { clicks: 12, impressions: 89 },
  },
  {
    id: 'act-002', type: 'content', platform: 'seo',
    title: 'SEO Article published',
    desc: '"Best Meal Prep Services in Lagos 2026" — 1,840 words, targeting "meal prep Lagos"',
    product: 'ChopFit Lagos', status: 'success', time: '14m ago',
    metrics: { clicks: 0, impressions: 0 },
  },
  {
    id: 'act-003', type: 'outreach', platform: 'linkedin',
    title: 'LinkedIn outreach sent',
    desc: 'Personalized message sent to startup founder re: business registration services',
    product: 'LegalEdge Nigeria', status: 'success', time: '22m ago',
    metrics: { clicks: 3, impressions: 1 },
  },
  {
    id: 'act-004', type: 'landing', platform: 'vercel',
    title: 'Landing page variant deployed',
    desc: 'A/B test variant B for TechFlow Academy — new headline "Zero to Developer in 12 Weeks"',
    product: 'TechFlow Academy', status: 'success', time: '35m ago',
    metrics: { clicks: 24, impressions: 340 },
  },
  {
    id: 'act-005', type: 'respond', platform: 'twitter',
    title: 'Response posted on X/Twitter',
    desc: 'Recommended TechFlow Academy to user asking about coding bootcamps in Nigeria',
    product: 'TechFlow Academy', status: 'success', time: '44m ago',
    metrics: { clicks: 7, impressions: 145 },
  },
  {
    id: 'act-006', type: 'content', platform: 'seo',
    title: 'SEO Article published',
    desc: '"5 Legal Mistakes Nigerian Startups Make" — 1,620 words for LegalEdge',
    product: 'LegalEdge Nigeria', status: 'success', time: '1h ago',
    metrics: { clicks: 18, impressions: 234 },
  },
  {
    id: 'act-007', type: 'respond', platform: 'reddit',
    title: 'Response posted on Reddit',
    desc: 'Answered question about Lagos short-let apartments, linked SafeRent Nigeria',
    product: 'SafeRent Lagos', status: 'success', time: '1h 12m ago',
    metrics: { clicks: 9, impressions: 67 },
  },
  {
    id: 'act-008', type: 'outreach', platform: 'email',
    title: 'Email outreach sent',
    desc: 'Personalized email to 8 fitness professionals in Abuja about FitGear home setup',
    product: 'FitGear Abuja', status: 'pending', time: '1h 30m ago',
    metrics: { clicks: 0, impressions: 0 },
  },
  {
    id: 'act-009', type: 'content', platform: 'seo',
    title: 'SEO Article queued',
    desc: '"Best Short-Let Apartments in Lagos 2026" — generation in progress',
    product: 'SafeRent Lagos', status: 'processing', time: '1h 45m ago',
    metrics: { clicks: 0, impressions: 0 },
  },
  {
    id: 'act-010', type: 'respond', platform: 'nairaland',
    title: 'Response posted on Nairaland',
    desc: 'Answered thread about Lagos accommodation for relocating professionals',
    product: 'SafeRent Lagos', status: 'success', time: '2h ago',
    metrics: { clicks: 22, impressions: 178 },
  },
]

export const PLATFORM_CHANNELS = [
  { id: 'twitter',   name: 'X / Twitter',  status: 'active',  signals: 89,  actionsToday: 3, limit: 3,  color: '#60a5fa' },
  { id: 'nairaland', name: 'Nairaland',    status: 'active',  signals: 124, actionsToday: 4, limit: 6,  color: '#fb923c' },
  { id: 'reddit',    name: 'Reddit',       status: 'active',  signals: 56,  actionsToday: 2, limit: 5,  color: '#f97316' },
  { id: 'linkedin',  name: 'LinkedIn',     status: 'active',  signals: 34,  actionsToday: 8, limit: 20, color: '#60a5fa' },
  { id: 'instagram', name: 'Instagram',    status: 'limited', signals: 28,  actionsToday: 1, limit: 3,  color: '#f472b6' },
  { id: 'google',    name: 'Google Search',status: 'active',  signals: 67,  actionsToday: 0, limit: 0,  color: '#60a5fa' },
  { id: 'email',     name: 'Email Outreach',status:'active',  signals: 0,   actionsToday: 8, limit: 20, color: '#a78bfa' },
  { id: 'quora',     name: 'Quora',        status: 'active',  signals: 21,  actionsToday: 1, limit: 3,  color: '#f87171' },
]

export const PERFORMANCE_DATA = {
  weekly: [
    { day: 'Mon', signals: 42, actions: 18, leads: 6 },
    { day: 'Tue', signals: 68, actions: 24, leads: 11 },
    { day: 'Wed', signals: 55, actions: 31, leads: 9 },
    { day: 'Thu', signals: 91, actions: 42, leads: 18 },
    { day: 'Fri', signals: 84, actions: 38, leads: 15 },
    { day: 'Sat', signals: 47, actions: 19, leads: 7 },
    { day: 'Sun', signals: 62, actions: 28, leads: 12 },
  ],
  monthly: [
    { month: 'Jan', signals: 820, actions: 340, leads: 89 },
    { month: 'Feb', signals: 1040, actions: 468, leads: 124 },
    { month: 'Mar', signals: 1380, actions: 612, leads: 178 },
    { month: 'Apr', signals: 1520, actions: 694, leads: 203 },
  ],
  byPlatform: [
    { platform: 'Nairaland',  signals: 498, actions: 187, leads: 67 },
    { platform: 'X/Twitter',  signals: 356, actions: 134, leads: 42 },
    { platform: 'Reddit',     signals: 224, actions: 89,  leads: 28 },
    { platform: 'LinkedIn',   signals: 178, actions: 142, leads: 51 },
    { platform: 'Instagram',  signals: 134, actions: 56,  leads: 19 },
    { platform: 'Google/SEO', signals: 268, actions: 86,  leads: 24 },
  ],
  funnel: [
    { stage: 'Signals Detected', value: 1520, pct: 100 },
    { stage: 'Qualified Matches', value: 986, pct: 64.9 },
    { stage: 'Actions Taken', value: 694, pct: 45.7 },
    { stage: 'Content Seen', value: 412, pct: 27.1 },
    { stage: 'Leads Generated', value: 203, pct: 13.4 },
  ],
}

export const COST_BREAKDOWN = [
  { service: 'LLM API (Claude — generation + analysis)', cost: '$58' },
  { service: 'Embeddings API (vector matching)', cost: '$2' },
  { service: 'X API Basic tier', cost: '$100' },
  { service: 'SerpAPI (5,000 searches/month)', cost: '$50' },
  { service: 'Residential Proxies (~10GB)', cost: '$75' },
  { service: 'Hosting (Vercel Pro)', cost: '$20' },
  { service: 'Email Service (SendGrid Pro)', cost: '$15' },
  { service: 'Vector Database (Pinecone)', cost: '$35' },
  { service: 'Server Infrastructure (VPS)', cost: '$60' },
]

export const SUMMARY_STATS = {
  activeProducts: 4,
  signalsToday: 449,
  actionsToday: 94,
  leadsToday: 31,
  signalsChange: '+18%',
  actionsChange: '+24%',
  leadsChange: '+12%',
}
